# Generated by Django 2.0 on 2020-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200203_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='default1.png', upload_to='Teachers/%Y/%m', verbose_name='教师头像'),
        ),
    ]
