# Generated by Django 2.0 on 2020-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='olds',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
