"""
Django settings for muxue project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e8uqi68a2-vtdg1($wop52n@bw2ed4b#39noy0vwbh0z2bw7j_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost','127.0.0.1',"101.200.132.67"]# 填写阿里云服务器地址

# Application definition
AUTHENTICATION_BACKENDS = (
	'users.views.CustomBackend',
)
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'users',
	'courses',
	'organization',
	'operation',
	'xadmin',
	'crispy_forms',
	'captcha',
	'pure_pagination',
	'DjangoUeditor',
]
AUTH_USER_MODEL = "users.Userprofile"

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'muxue.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')]
		,
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				##配置media
				'django.template.context_processors.media',
			],
		},
	},
]

WSGI_APPLICATION = 'muxue.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# 配置服务器地址
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': '创建的数据库名称',
		'USER': 'root',
		'PASSWORD': '登陆密码',
		'HOST': '127.0.0.1',
		'PORT': '3306',
	},
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 解决：配置正确，而网页中文件无法加载的问题
STATICFILES_DIRS = (
	('css', os.path.join(STATIC_ROOT, 'css').replace('\\', '/')),
	('js', os.path.join(STATIC_ROOT, 'js').replace('\\', '/')),
	('images', os.path.join(STATIC_ROOT, 'images').replace('\\', '/')),
)

# 配置用户上传的文件
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 需要配置TEMPLATES
# MEDIA_ROOT = 'C:/Users/HongjieGuo/Desktop/muxue/static'

# 发送邮件设置
EMAIL_HOST = 'smtp.qq.com'  # 使用SMTP服务器，需要在邮箱中开启此服务
EMAIL_PORT = 587
EMAIL_HOST_USER = '1725128685@qq.com'
EMAIL_HOST_PASSWORD = 'axmoyvogwnfqfdcb'

EMAIL_FROM = '1725128685@qq.com'  # 自定义配置，使用时需要引入

# 分页器
PAGINATION_SETTINGS = {
	'PAGE_RANGE_DISPLAYED': 10,  # 中间显
