# Generated by Django 2.0 on 2020-01-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '资源下载', 'verbose_name_plural': '资源下载'},
        ),
    ]
