# Generated by Django 2.0 on 2020-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tell_you',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你什么'),
        ),
    ]
