# Generated by Django 2.0 on 2020-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200207_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to='Video/%Y/%m', verbose_name='视频文件'),
            preserve_default=False,
        ),
    ]
