# Generated by Django 2.0 on 2020-02-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200211_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.png', upload_to='courses/%Y/%m', verbose_name='封面'),
        ),
    ]
