# Generated by Django 2.0 on 2020-02-12 17:11

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200212_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程描述'),
        ),
    ]
