# Generated by Django 2.0 on 2020-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200212_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.CharField(default='', max_length=200, verbose_name='课程描述'),
        ),
    ]
