# Generated by Django 2.0 on 2020-01-31 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200129_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfyrecode',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverfyrecode',
            name='type',
            field=models.CharField(choices=[('register', '注册'), ('froget', '找回密码')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
