# Generated by Django 2.0 on 2020-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200131_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfyrecode',
            name='type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
