# Generated by Django 2.0 on 2020-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200131_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverfyrecode',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
        ),
    ]
