# Generated by Django 2.0 on 2020-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200205_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfyrecode',
            name='type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update', '重置密码')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
